name: Workflow dispatch

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  dev:
    name: Deploy to dev ${{ github.run_number }}
    runs-on: ubuntu-latest
    needs: build
    env:
      VERSION: ${{ github.run_number }}
    outputs:
      VERSION: ${{ steps.build.outputs.VERSION }}
    steps:
      - name: Set version
        id: set_version
        run: echo "::set-output name=VERSION::${{ github.run_number }}"
      - name: Deploy to dev
        run: |
          echo "Deploying to dev. Version:${{ needs.dev.outputs.VERSION }}"
  staging:
    name: Deploy to staging ${{ needs.dev.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: [dev]
    if: github.event.inputs.environment == 'staging' && github.event_name == 'workflow_dispatch'
    env:
      VERSION: ${{ needs.dev.outputs.VERSION }}
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging. Version: ${{ needs.dev.outputs.VERSION }}"

  production:
    name: Deploy to production ${{ needs.dev.outputs.VERSION }}
    runs-on: ubuntu-latest
    needs: [staging]
    if: github.event.inputs.environment == 'production' && github.event_name == 'workflow_dispatch'
    env:
      VERSION: ${{ needs.dev.outputs.VERSION }}
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production. Version: ${{ needs.dev.outputs.VERSION }}"
