name: Workflow dispatch

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  dev:
    name: Deploy to dev ${{ github.run_number }}
    needs: build
    runs-on: ubuntu-latest
    outputs:
      PACKAGE: ${{ steps.build.outputs.PACKAGE }}
    steps:
      - name: Build
        id: build
        run: echo "::set-output name=PACKAGE::${{github.run_number}}-dev.tar.gz"
      - name: Get version
        id: version
        run: echo "::set-output name=VERSION::${{ github.run_number }}"
      - name: Deploy to dev
        run: |
          echo "Deploying to dev. Version: ${{ github.run_number }}"

  staging:
    name: Deploy to staging ${{ github.run_number }}
    needs: [build, dev]
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'staging' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging. Package: ${{ needs.dev.outputs.PACKAGE }}"

  production:
    name: Deploy to production ${{ github.run_number }}
    needs: [build, dev, staging]
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production. Package: ${{ needs.dev.outputs.PACKAGE }}"
