name: Workflow dispatch

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x.x"
      - name: Seutup appsettings
        run: cp appsettings.json.example  appsettings.json
      - name: Substitute appsettings.json values
        uses: actions/variable-substitution@v3
        with:
          files: appsettings.json
          variables:
            Example: "new Example"

      - name: Setup environment variables
        run: |
          echo "PACKAGE=${{ env.PACKAGE }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  deploy:
    name: Deploy to ${{ github.environment.name }} ${{ github.run_number }}
    runs-on: ubuntu-latest
    # if it is staging then it should be dev and when it is production then it should be staging
    needs: [build]
    steps:
      - name: Deploy to ${{ github.environment.name }}
        run: |
          echo digggudg run_number ${{ env.PACKAGE }}
