name: Workflow dispatch

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE: ${{ steps.package.outputs.PACKAGE }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.x.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  deploy:
    name: Deploy to ${{ github.environment.name }} ${{ github.run_number }}
    runs-on: ubuntu-latest
    # if it is staging then it should be dev and when it is production then it should be staging
    needs: [build]
    steps:
      - name: Deploy to $${{ github.environment.name }}
        run: |
          echo $PACKAGE
